import {
  Activity,
  BookOpen,
  ClipboardList,
  Crown,
  Database,
  Download,
  HeartPulse,
  Home,
  ImageIcon,
  Receipt,
  ShieldCheck,
  ShoppingCart,
  Stethoscope,
  User,
  Users,
  Utensils,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type WorkspaceRole = 'USER' | 'NUTRITIONIST' | 'ADMIN';
export type WorkspaceTool = { label: string; href: string; description: string; group: string; icon: LucideIcon };
export const workspaceLabels: Record<WorkspaceRole, string> = {
  USER: 'Personal workspace',
  NUTRITIONIST: 'Nutritionist workspace',
  ADMIN: 'Administrator workspace',
};
export const workspaceTools: Record<WorkspaceRole, WorkspaceTool[]> = {
  USER: [
    {
      label: 'Dashboard',
      href: '/dashboard',
      description: 'Daily meals, nutrition totals, water, and check-ins.',
      group: 'Every day',
      icon: Home,
    },
    {
      label: 'Meal plan',
      href: '/meals',
      description: 'Your weekly plan, meal history, swaps, and library.',
      group: 'Every day',
      icon: Utensils,
    },
    {
      label: 'Grocery',
      href: '/grocery',
      description: 'Approved ingredients, pantry items, and shopping PDF.',
      group: 'Every day',
      icon: ShoppingCart,
    },
    {
      label: 'Progress',
      href: '/progress',
      description: 'Log weight and follow your nutrition history.',
      group: 'Your health',
      icon: Activity,
    },
    {
      label: 'Health profile',
      href: '/health-profile',
      description: 'Goals, conditions, allergies, location, and food preferences.',
      group: 'Your health',
      icon: HeartPulse,
    },
    {
      label: 'Premium access',
      href: '/billing',
      description: 'View your plan, entitlements, and payment status.',
      group: 'Your account',
      icon: Crown,
    },
    {
      label: 'Account profile',
      href: '/profile',
      description: 'Personal details, avatar, and account security.',
      group: 'Your account',
      icon: User,
    },
    {
      label: 'Exports',
      href: '/export',
      description: 'Download available nutrition and meal-plan reports.',
      group: 'Your account',
      icon: Download,
    },
  ],
  NUTRITIONIST: [
    {
      label: 'Review queue',
      href: '/nutritionist/reviews',
      description: 'Claim, inspect, correct, and review meal-plan rows.',
      group: 'Review work',
      icon: ClipboardList,
    },
    {
      label: 'Outside meals',
      href: '/nutritionist/outside-meals',
      description: 'Verify itemized food logs and correct nutrition estimates.',
      group: 'Review work',
      icon: Utensils,
    },
    {
      label: 'Approved plans',
      href: '/nutritionist/approved',
      description: 'Revisit your completed meal-plan reviews.',
      group: 'Review work',
      icon: ShieldCheck,
    },
    {
      label: 'Meal library',
      href: '/nutritionist/library',
      description: 'Manage recipes, ingredient evidence, and flags.',
      group: 'Professional tools',
      icon: BookOpen,
    },
    {
      label: 'Compensation',
      href: '/nutritionist/compensation',
      description: 'Review work credits, statements, and payout records.',
      group: 'Professional tools',
      icon: Receipt,
    },
    {
      label: 'Professional profile',
      href: '/nutritionist/profile',
      description: 'Your credentials, PRC license, and specialization.',
      group: 'Professional tools',
      icon: Stethoscope,
    },
  ],
  ADMIN: [
    {
      label: 'Overview',
      href: '/admin/overview',
      description: 'Account totals, review queues, and platform signals.',
      group: 'Platform',
      icon: Home,
    },
    {
      label: 'Analytics',
      href: '/admin/analytics',
      description: 'Explore nutrition and usage trends.',
      group: 'Platform',
      icon: Activity,
    },
    {
      label: 'Operations',
      href: '/admin/operations',
      description: 'Monitor processing, reconciliation, and operational status.',
      group: 'Platform',
      icon: ShieldCheck,
    },
    {
      label: 'Users',
      href: '/admin/users',
      description: 'Search and manage user accounts.',
      group: 'People',
      icon: Users,
    },
    {
      label: 'Nutritionists',
      href: '/admin/nutritionists',
      description: 'Applications, credential screening, and PRC verification.',
      group: 'People',
      icon: Stethoscope,
    },
    {
      label: 'Compensation',
      href: '/admin/compensation',
      description: 'Work policies, statements, adjustments, and payout records.',
      group: 'People',
      icon: Receipt,
    },
    {
      label: 'Nutrition data',
      href: '/admin/data',
      description: 'Sources, releases, imports, publication, and FNRI catalogue.',
      group: 'Content & evidence',
      icon: Database,
    },
    {
      label: 'Meal images',
      href: '/admin/images',
      description: 'Assign and review meal photographs and attribution.',
      group: 'Content & evidence',
      icon: ImageIcon,
    },
  ],
};
